env:
  global:
    - secure: IdqEArwpiD8WbH4D+lxFoeyspcoqgX6Spu4Pg0JTmwwR29Y4WLbmKbBit5lu8NU1JlgpGDiClU6iKsN0WBd2tDy7e4xrV4k8uXKS7UksCkP4/g7CVeOTQB4dwHIosbMNbRZf3w7kkXicSUf5ILNSb1E9YQi8MQHNMA3OmO76iNCXzjs7UidOjCcXxJQ04aMoW7HKMhcsHnUgIZlS0qmwmHjRViDkB23G+h3baWBl9pWkvGMwHh681lmIYwwWQpLfGxsQLYfu0VEG6sfyFhiWyW0337Ak8kOpA7gmf9YGv+RD6TJO8gx974JzAF6HXoijb1mzMK7k3oe+AMwQDutcWzE/zN+LFIhY9n+FhMXSTh5hVQjgVuSUCqBIMQSSRiIRv82lcA8fOAagw4Cc8Z4JwWypkp5pqx/1ZXJdGxmjQBTbh5aN3rHlvQNRqaRFUckJT7TtzMnWY9oL2cvli1MdLJaEeIlJPehJyNsOwOi//H7ROmwAPc88cQKzfK0CGrPtvbWouIBQdjjHigZ8g2h8ekkBiX+iMbunhNazv1VDsB9ZgWU8pnwt4Rt9vBmDHp2AQc35n4z4yj0a4F2G6f8qejEmiXpUggvHkAictqiNyMvKvMaTSELIJvAJHcXYrGBd6R49LYnRoISjClNOJuIUMAblAr9k+ZxNlGd7zrlPcMI=
    - secure: VKP7z65a3fJilGDWIcU0jDHqAS22mafpkjPoWLyC1VNEftqeFSdEuay87BLjEj3HHUFaCfb4LnIVMF/3ZffK/jrYBH6nsvXqaq3/GGLPB2L7wSQd00tcRlivXZAd8Mv82OikzpBGI0duhPmV6zLxXbOaG7CLGpAIIJFdZcEua1DdfehppTASDp3Vmo9ul+/q13Nx63nJ20p34Jf9wpoEHRwDHx0UyNmoIoXXRiKrVWastRucSMb9L7E8UTYHpr97iVlNlaawVMv/oBXqGiFbN8aV39FeZpdCoXW1VH+5CYzecOfsJEGdVm9FtE1Z9EpNAfGd9AkngZs2D+edH+4NM2GZIYcUAuXCjyKb7JTakH7rgnP3CmWLY2kzgQTjUbOhA/eD5OJenGdENkxR0mN0vaw+EqEP/0GJDyEHz3rmcyfgCGpHyIJgBze3QUCWgFNqG7M6FO2kwVKsid4igXgHnP2Ls0RJA6VGHH3noHgeKZFqx9ssWNPlrA/MegfhCMwUsH74aFBOQaKXNO1uA4znJxgaAf+UBWKkM8YPzCzWmNZk5x1ZjoDplCNqGfK6ui6BBLWwwEH2Lslz3fNMsyv9qgd03O+qkUcWkuMOKkWP5svrcZE4DbmoqxnjunwiXVmFNeb9E31vin4h/dVzeyWsCZtLztzgSMNGWCpMAUhyKI4=
language: python
matrix:
  include:
    - python: 3.6
      env:
        - TOXENV=py36
install:
  - pip install tox coveralls
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - "./cc-test-reporter before-build"
script:
  - tox
after_success:
  - coveralls
  - coverage xml
  - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
deploy:
  provider: pypi
  user: breatheoften
  distributions: sdist bdist_wheel
  on:
    condition: "$TOXENV == py36"
    tags: true
    all_branches: true
    repo: breathe/NotebookScripter
  password:
    secure: u+mhGWnbQ53VJvNhLwuWQ1PrgOQi/fVn4M3KDUOfUp955x2mDmUU3b2FpQ2KMrzmMqhXPvcKPkVoa0hUoKmXBsc7eVcIRfotHqwt9Uuigr9P7ApKBgiBsFboAC26H+pZbKRaOVn/V26ajHWWtn7jr0bvsFJi8MCtXKufgMQCPtTZR2t94nhmdQVfPYK4mnuSHc2nvE7x7QbZ7X7ldQno4WILWe7vI+A+FcV7NlxjVNkbG/zBjC82qN2mN/jQJg4MwurFszQ07iX5N6TTtysjQBnHX9VcMCWW33q2LETsY8PZ4UQRQls/+YRMe9+72/usF1aUpxIngh07SRz7w4a9/EhFE4jYaO5lQGDzUfZ6yTEK3nyN+piD199zZ6Ahk74TXSCKmXG2pQyqTrDTV8d5q2B5qxvnxAW+qlTy3Q6lrMPgtyNB7ebInSh07B+YTNcDYI4Yu55pqMfu3ss20qDyse0KLbcnhGRJI/HU9IEjgjSI5bvxSlfOxuaIlHJp3GBDjBf9EDLm4cvKU/taX6sTbAEs01if3zHZOBXHvUzP922DRezme5SCOQIgveXyEBk3kRSvoAzsuNXSl1TFBNCFlYv26gDt4aDSAtspCqim3KDrqHMt7M9DAzUN1UKOgCajnke/Mjff/yrYr9wCsHVrs4qyuwc3HA2JC66oKs/FOc0=
